x=int(input("Enter the first element:"))
y=int(input("Enter the second element:"))
print("Below some basic operations:")
print("Addition is:",(x+y))
print("Subtraction is:",(x-y))
print("Multiplication is:",(x*y))
print("Division is:",(x/y))
print("Division is:",(x//y))
print("Exponent is:",(x**y))
print("Modulo is:",(x%y))
